name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: pip install pyyaml
      - run: pip install -r requirements_dev.txt
      - run: py.test -vvs tests
      - run: pip uninstall -y pyyaml
      - run: pip install pyyaml
      - run: py.test -vvs tests